#!/usr/bin/env node
import { readFileSync, writeFileSync } from "node:fs";
import { basename, resolve } from "node:path";

const base = process.argv[2];
if (!base) {
  console.error("usage: generate-wrapper.mjs <wasm-bindgen-module-base>");
  process.exit(1);
}

const moduleBase = resolve(base).replace(/\.(d\.ts|js|ts)$/, "");
const dtsPath = `${moduleBase}.d.ts`;
const outputPath = `${moduleBase}_stores.ts`;
const moduleName = `./${basename(moduleBase)}`;
const source = readFileSync(dtsPath, "utf8");
const kinds = parseStoreKinds(source);

writeFileSync(outputPath, renderWrapper(moduleName, kinds));
console.log(`generated ${outputPath}`);

function parseStoreKinds(source) {
  const match = source.match(/export interface StoreKinds\s*{([\s\S]*?)\n}/);
  if (!match) {
    throw new Error(`StoreKinds interface not found in ${dtsPath}`);
  }

  const entries = [...match[1].matchAll(/^\s*([A-Za-z_$][\w$]*)\s*:\s*"([^"]+)";/gm)].map(
    ([, name, kind]) => ({ name, kind }),
  );

  if (entries.length === 0) {
    throw new Error(`StoreKinds interface is empty in ${dtsPath}`);
  }

  for (const entry of entries) {
    if (!["atom", "map", "readable"].includes(entry.kind)) {
      throw new Error(`unsupported store kind ${entry.kind} for ${entry.name}`);
    }
  }

  return entries;
}

function renderWrapper(moduleName, kinds) {
  const storeKinds = kinds.map(({ name, kind }) => `  ${name}: "${kind}",`).join("\n");

  return `// Generated by packages/nanostores-wasm/scripts/generate-wrapper.mjs.
// Do not edit by hand.
import { projectStores } from "nanostores-wasm";
import initWasmCore, {
  stores as rawStores,
  type ProjectedStoreHandles,
  type StoreKinds,
} from "${moduleName}";

const STORE_KINDS = {
${storeKinds}
} as const satisfies StoreKinds;

export type AppStores = ProjectedStoreHandles;

let wasmReady: Promise<unknown> | undefined;

/** Initializes the wasm module on first call and projects every exported
 * store into a real nanostores store. */
export async function createStores(): Promise<AppStores> {
  wasmReady ??= initWasmCore();
  await wasmReady;
  return projectStores(rawStores(), STORE_KINDS) as AppStores;
}
`;
}
